version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mensageria_mysql
    restart: always
    environment:
      MYSQL_DATABASE: mensageria_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"